name: Deploy to Firebase Hosting for App on PR
'on': pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Creating & Initializing env variables for App Package
        run: |
          cd packages/app
          pwd
          echo "VITE_KAIMA_APP_API_KEY= ${{secrets.VITE_KAIMA_APP_API_KEY}}
          VITE_KAIMA_APP_AUTH_DOMAIN= ${{secrets.VITE_KAIMA_APP_AUTH_DOMAIN}}
          VITE_KAIMA_APP_PROJECT_ID= ${{secrets.VITE_KAIMA_APP_PROJECT_ID}}
          VITE_KAIMA_APP_STORAGE_BUCKET= ${{secrets.VITE_KAIMA_APP_STORAGE_BUCKET}}
          VITE_KAIMA_APP_MESSAGING_SENDER_ID= ${{secrets.VITE_KAIMA_APP_MESSAGING_SENDER_ID}}
          VITE_KAIMA_APP_APP_ID= ${{secrets.VITE_KAIMA_APP_APP_ID}}
          VITE_KAIMA_APP_MEASUREMENT_ID= ${{secrets.VITE_KAIMA_APP_MEASUREMENT_ID}}" > .env

      - name: Build the project
        run: |
          yarn
          yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KA_IMA }}'
          projectId: ka-ima
